name: Update Sponsors

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 */4 * * *"  # 每四小时运行一次
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run update_sponsors.py
        env:
          AFDIAN_USER_ID: ${{ secrets.AFDIAN_USER_ID }}
          AFDIAN_TOKEN: ${{ secrets.AFDIAN_TOKEN }}
        run: python update_sponsors.py

      - name: Create README.md if it doesn't exist
        run: |
          if [ ! -f "README.md" ]; then
            echo "# Project Title" > README.md
            echo "This is an automatically generated README file." >> README.md
          fi

      - name: Create sponsors.json if it doesn't exist
        run: |
          if [ ! -f "sponsors.json" ]; then
            echo '{}' > sponsors.json
          fi

      - name: Commit & push README and sponsors updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # 添加 README.md 和 sponsors.json 文件
          git add README.md
          git add sponsors.json
          
          # 如果有更改，提交并推送
          if ! git diff --staged --quiet; then
            git commit -m "update sponsors"
            git push
          fi